<?php

/**
 * This is the model base class for the table "user_rules_menu".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserRulesMenu".
 *
 * Columns in table "user_rules_menu" available as properties of the model,
 * followed by relations of table "user_rules_menu" available as properties of the model.
 *
 * @property string $id
 * @property string $parent_id
 * @property string $rule_id
 * @property string $module_id
 * @property string $label
 * @property string $url
 * @property integer $position
 * @property integer $is_active
 *
 * @property Module $module
 * @property UserRules $rule
 */
abstract class BaseUserRulesMenu extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'user_rules_menu';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UserRulesMenu|UserRulesMenus', $n);
	}

	public static function representingColumn() {
		return 'label';
	}

	public function rules() {
		return array(
			array('label, url, position, is_active', 'required'),
			array('position, is_active', 'numerical', 'integerOnly'=>true),
			array('parent_id, rule_id, module_id', 'length', 'max'=>10),
			array('label', 'length', 'max'=>50),
			array('url', 'length', 'max'=>255),
			array('parent_id, rule_id, module_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, parent_id, rule_id, module_id, label, url, position, is_active', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'module' => array(self::BELONGS_TO, 'Module', 'module_id'),
			'rule' => array(self::BELONGS_TO, 'UserRules', 'rule_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'parent_id' => Yii::t('app', 'Parent'),
			'rule_id' => null,
			'module_id' => null,
			'label' => Yii::t('app', 'Label'),
			'url' => Yii::t('app', 'Url'),
			'position' => Yii::t('app', 'Position'),
			'is_active' => Yii::t('app', 'Is Active'),
			'module' => null,
			'rule' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('parent_id', $this->parent_id, true);
		$criteria->compare('rule_id', $this->rule_id);
		$criteria->compare('module_id', $this->module_id);
		$criteria->compare('label', $this->label, true);
		$criteria->compare('url', $this->url, true);
		$criteria->compare('position', $this->position);
		$criteria->compare('is_active', $this->is_active);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}