<?php

/**
 * This is the model base class for the table "module".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Module".
 *
 * Columns in table "module" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $module_code
 * @property string $version
 * @property integer $is_publish
 *
 */
abstract class BaseModule extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'module';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Module|Modules', $n);
	}

	public static function representingColumn() {
		return 'module_code';
	}

	public function rules() {
		return array(
			array('is_publish', 'numerical', 'integerOnly'=>true),
			array('module_code, version', 'length', 'max'=>50),
			array('module_code, version, is_publish', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, module_code, version, is_publish', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'module_code' => Yii::t('app', 'Module Code'),
			'version' => Yii::t('app', 'Version'),
			'is_publish' => Yii::t('app', 'Is Publish'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('module_code', $this->module_code, true);
		$criteria->compare('version', $this->version, true);
		$criteria->compare('is_publish', $this->is_publish);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}