<?php

/**
 * This is the model base class for the table "subscription_video_transaction".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SubscriptionVideoTransaction".
 *
 * Columns in table "subscription_video_transaction" available as properties of the model,
 * followed by relations of table "subscription_video_transaction" available as properties of the model.
 *
 * @property integer $subscription_id
 * @property integer $video_id
 * @property integer $additional_status
 *
 * @property Videos $video
 * @property PackageSubscription $subscription
 */
abstract class BaseSubscriptionVideoTransaction extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'subscription_video_transaction';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'SubscriptionVideoTransaction|SubscriptionVideoTransactions', $n);
	}

	public static function representingColumn() {
		return 'subscription_id';
	}

	public function rules() {
		return array(
			array('subscription_id, video_id, additional_status', 'numerical', 'integerOnly'=>true),
			array('subscription_id, video_id, additional_status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('subscription_id, video_id, additional_status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'video' => array(self::BELONGS_TO, 'Videos', 'video_id'),
			'subscription' => array(self::BELONGS_TO, 'PackageSubscription', 'subscription_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'subscription_id' => null,
			'video_id' => null,
			'additional_status' => Yii::t('app', 'Additional Status'),
			'video' => null,
			'subscription' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('subscription_id', $this->subscription_id);
		$criteria->compare('video_id', $this->video_id);
		$criteria->compare('additional_status', $this->additional_status);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}