<?php

/**
 * This is the model base class for the table "state_master".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "StateMaster".
 *
 * Columns in table "state_master" available as properties of the model,
 * followed by relations of table "state_master" available as properties of the model.
 *
 * @property integer $id
 * @property integer $country_id
 * @property string $state_name
 * @property string $state_abbv
 * @property integer $status
 *
 * @property CountryMaster $country
 * @property Users[] $users
 */
abstract class BaseStateMaster extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'state_master';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'StateMaster|StateMasters', $n);
	}

	public static function representingColumn() {
		return 'state_name';
	}

	public function rules() {
		return array(
			array('country_id, status', 'numerical', 'integerOnly'=>true),
			array('state_name, state_abbv', 'length', 'max'=>255),
			array('country_id, state_name, state_abbv, status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, country_id, state_name, state_abbv, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'country' => array(self::BELONGS_TO, 'CountryMaster', 'country_id'),
			'users' => array(self::HAS_MANY, 'Users', 'state_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'country_id' => null,
			'state_name' => Yii::t('app', 'State Name'),
			'state_abbv' => Yii::t('app', 'State Abbv'),
			'status' => Yii::t('app', 'Status'),
			'country' => null,
			'users' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('country_id', $this->country_id);
		$criteria->compare('state_name', $this->state_name, true);
		$criteria->compare('state_abbv', $this->state_abbv, true);
		$criteria->compare('status', $this->status);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}