<?php

/**
 * This is the model base class for the table "package_subscription_transaction".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PackageSubscriptionTransaction".
 *
 * Columns in table "package_subscription_transaction" available as properties of the model,
 * followed by relations of table "package_subscription_transaction" available as properties of the model.
 *
 * @property integer $package_id
 * @property integer $subscription_id
 * @property integer $additional_status
 *
 * @property PackageSubscription $package
 * @property PackageSubscription $subscription
 */
abstract class BasePackageSubscriptionTransaction extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'package_subscription_transaction';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PackageSubscriptionTransaction|PackageSubscriptionTransactions', $n);
	}

	public static function representingColumn() {
		return 'package_id';
	}

	public function rules() {
		return array(
			array('package_id, subscription_id, additional_status', 'numerical', 'integerOnly'=>true),
			array('package_id, subscription_id, additional_status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('package_id, subscription_id, additional_status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'package' => array(self::BELONGS_TO, 'PackageSubscription', 'package_id'),
			'subscription' => array(self::BELONGS_TO, 'PackageSubscription', 'subscription_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'package_id' => null,
			'subscription_id' => null,
			'additional_status' => Yii::t('app', 'Additional Status'),
			'package' => null,
			'subscription' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('package_id', $this->package_id);
		$criteria->compare('subscription_id', $this->subscription_id);
		$criteria->compare('additional_status', $this->additional_status);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}