<?php

/**
 * This is the model base class for the table "user_purchased_videos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserPurchasedVideos".
 *
 * Columns in table "user_purchased_videos" available as properties of the model,
 * followed by relations of table "user_purchased_videos" available as properties of the model.
 *
 * @property string $id
 * @property integer $user_id
 * @property integer $package_id
 * @property integer $subscription_id
 * @property integer $video_id
 * @property integer $is_updated
 * @property string $updated_on
 *
 * @property Users $user
 * @property PackageSubscription $subscription
 * @property PackageSubscription $package
 * @property Videos $video
 */
abstract class BaseUserPurchasedVideos extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'user_purchased_videos';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UserPurchasedVideos|UserPurchasedVideoses', $n);
	}

	public static function representingColumn() {
		return 'updated_on';
	}

	public function rules() {
		return array(
			array('user_id, package_id, subscription_id, video_id, is_updated', 'numerical', 'integerOnly'=>true),
			array('updated_on', 'safe'),
			array('user_id, package_id, subscription_id, video_id, is_updated, updated_on', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, package_id, subscription_id, video_id, is_updated, updated_on', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'Users', 'user_id'),
			'subscription' => array(self::BELONGS_TO, 'PackageSubscription', 'subscription_id'),
			'package' => array(self::BELONGS_TO, 'PackageSubscription', 'package_id'),
			'video' => array(self::BELONGS_TO, 'Videos', 'video_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'package_id' => null,
			'subscription_id' => null,
			'video_id' => null,
			'is_updated' => Yii::t('app', 'Is Updated'),
			'updated_on' => Yii::t('app', 'Updated On'),
			'user' => null,
			'subscription' => null,
			'package' => null,
			'video' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('package_id', $this->package_id);
		$criteria->compare('subscription_id', $this->subscription_id);
		$criteria->compare('video_id', $this->video_id);
		$criteria->compare('is_updated', $this->is_updated);
		$criteria->compare('updated_on', $this->updated_on, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}