<?php

/**
 * This is the model base class for the table "cart".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Cart".
 *
 * Columns in table "cart" available as properties of the model,
 * followed by relations of table "cart" available as properties of the model.
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $package_subscription_id
 * @property string $video_id
 * @property integer $duration
 * @property integer $is_admin_approved
 *
 * @property PackageSubscription $packageSubscription
 * @property Users $user
 */
abstract class BaseCart extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'cart';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Cart|Carts', $n);
	}

	public static function representingColumn() {
		return 'video_id';
	}

	public function rules() {
		return array(
			array('duration', 'required'),
			array('user_id, package_subscription_id, duration, is_admin_approved', 'numerical', 'integerOnly'=>true),
			array('video_id', 'length', 'max'=>255),
			array('user_id, package_subscription_id, video_id, is_admin_approved', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, package_subscription_id, video_id, duration, is_admin_approved', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'packageSubscription' => array(self::BELONGS_TO, 'PackageSubscription', 'package_subscription_id'),
			'user' => array(self::BELONGS_TO, 'Users', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'package_subscription_id' => null,
			'video_id' => Yii::t('app', 'Video'),
			'duration' => Yii::t('app', 'Duration'),
			'is_admin_approved' => Yii::t('app', 'Is Admin Approved'),
			'packageSubscription' => null,
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('package_subscription_id', $this->package_subscription_id);
		$criteria->compare('video_id', $this->video_id, true);
		$criteria->compare('duration', $this->duration);
		$criteria->compare('is_admin_approved', $this->is_admin_approved);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}