<?php

/**
 * This is the model base class for the table "orders_transaction".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "OrdersTransaction".
 *
 * Columns in table "orders_transaction" available as properties of the model,
 * followed by relations of table "orders_transaction" available as properties of the model.
 *
 * @property integer $id
 * @property integer $order_id
 * @property integer $user_id
 * @property integer $package_id
 * @property integer $subscription_id
 * @property integer $video_id
 * @property integer $total_available_video
 *
 * @property Videos $video
 * @property Orders $order
 * @property Users $user
 * @property PackageSubscription $subscription
 * @property PackageSubscription $package
 */
abstract class BaseOrdersTransaction extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'orders_transaction';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'OrdersTransaction|OrdersTransactions', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('order_id, user_id, package_id, subscription_id, video_id, total_available_video', 'numerical', 'integerOnly'=>true),
			array('order_id, user_id, package_id, subscription_id, video_id, total_available_video', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, order_id, user_id, package_id, subscription_id, video_id, total_available_video', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'video' => array(self::BELONGS_TO, 'Videos', 'video_id'),
			'order' => array(self::BELONGS_TO, 'Orders', 'order_id'),
			'user' => array(self::BELONGS_TO, 'Users', 'user_id'),
			'subscription' => array(self::BELONGS_TO, 'PackageSubscription', 'subscription_id'),
			'package' => array(self::BELONGS_TO, 'PackageSubscription', 'package_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'order_id' => null,
			'user_id' => null,
			'package_id' => null,
			'subscription_id' => null,
			'video_id' => null,
			'total_available_video' => Yii::t('app', 'Total Available Video'),
			'video' => null,
			'order' => null,
			'user' => null,
			'subscription' => null,
			'package' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('order_id', $this->order_id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('package_id', $this->package_id);
		$criteria->compare('subscription_id', $this->subscription_id);
		$criteria->compare('video_id', $this->video_id);
		$criteria->compare('total_available_video', $this->total_available_video);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}