<?php

/**
 * This is the model base class for the table "class_videos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ClassVideos".
 *
 * Columns in table "class_videos" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $class_id
 * @property integer $video_id
 *
 */
abstract class BaseClassVideos extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'class_videos';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ClassVideos|ClassVideoses', $n);
	}

	public static function representingColumn() {
		return array(
			'class_id',
			'video_id',
		);
	}

	public function rules() {
		return array(
			array('class_id, video_id', 'numerical', 'integerOnly'=>true),
			array('class_id, video_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('class_id, video_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'class_id' => null,
			'video_id' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('class_id', $this->class_id);
		$criteria->compare('video_id', $this->video_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}