<?php

/**
 * This is the model base class for the table "order_details".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "OrderDetails".
 *
 * Columns in table "order_details" available as properties of the model,
 * followed by relations of table "order_details" available as properties of the model.
 *
 * @property integer $id
 * @property integer $order_id
 * @property integer $package_subscription_id
 * @property string $start_date
 * @property string $expiry_date
 * @property double $amount
 * @property integer $duration
 *
 * @property Orders $order
 * @property PackageSubscription $packageSubscription
 */
abstract class BaseOrderDetails extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'order_details';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'OrderDetails|OrderDetails', $n);
	}

	public static function representingColumn() {
		return 'start_date';
	}

	public function rules() {
		return array(
			array('order_id, package_subscription_id, duration', 'numerical', 'integerOnly'=>true),
			array('amount', 'numerical'),
			array('start_date, expiry_date', 'safe'),
			array('order_id, package_subscription_id, start_date, expiry_date, amount, duration', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, order_id, package_subscription_id, start_date, expiry_date, amount, duration', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'order' => array(self::BELONGS_TO, 'Orders', 'order_id'),
			'packageSubscription' => array(self::BELONGS_TO, 'PackageSubscription', 'package_subscription_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'order_id' => null,
			'package_subscription_id' => null,
			'start_date' => Yii::t('app', 'Start Date'),
			'expiry_date' => Yii::t('app', 'Expiry Date'),
			'amount' => Yii::t('app', 'Amount'),
			'duration' => Yii::t('app', 'Duration'),
			'order' => null,
			'packageSubscription' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('order_id', $this->order_id);
		$criteria->compare('package_subscription_id', $this->package_subscription_id);
		$criteria->compare('start_date', $this->start_date, true);
		$criteria->compare('expiry_date', $this->expiry_date, true);
		$criteria->compare('amount', $this->amount);
		$criteria->compare('duration', $this->duration);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}