<?php

/**
 * This is the model base class for the table "user_videos_transaction".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserVideosTransaction".
 *
 * Columns in table "user_videos_transaction" available as properties of the model,
 * followed by relations of table "user_videos_transaction" available as properties of the model.
 *
 * @property integer $id
 * @property integer $order_id
 * @property integer $user_id
 * @property integer $class_id
 * @property integer $video_id
 *
 * @property Users $user
 * @property Classes $class
 * @property Orders $order
 * @property Videos $video
 */
abstract class BaseUserVideosTransaction extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'user_videos_transaction';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UserVideosTransaction|UserVideosTransactions', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('order_id, user_id, class_id, video_id', 'numerical', 'integerOnly'=>true),
			array('order_id, user_id, class_id, video_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, order_id, user_id, class_id, video_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'Users', 'user_id'),
			'class' => array(self::BELONGS_TO, 'Classes', 'class_id'),
			'order' => array(self::BELONGS_TO, 'Orders', 'order_id'),
			'video' => array(self::BELONGS_TO, 'Videos', 'video_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'order_id' => null,
			'user_id' => null,
			'class_id' => null,
			'video_id' => null,
			'user' => null,
			'class' => null,
			'order' => null,
			'video' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('order_id', $this->order_id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('class_id', $this->class_id);
		$criteria->compare('video_id', $this->video_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}