<?php

/**
 * This is the model base class for the table "newsletters_users".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "NewslettersUsers".
 *
 * Columns in table "newsletters_users" available as properties of the model,
 * followed by relations of table "newsletters_users" available as properties of the model.
 *
 * @property string $id
 * @property integer $user_id
 * @property string $email
 * @property integer $is_subscribed
 * @property string $created_at
 * @property string $updated_at
 *
 * @property Users $user
 */
abstract class BaseNewslettersUsers extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'newsletters_users';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'NewslettersUsers|NewslettersUsers', $n);
	}

	public static function representingColumn() {
		return 'email';
	}

	public function rules() {
		return array(
			array('user_id, is_subscribed', 'numerical', 'integerOnly'=>true),
			array('email', 'length', 'max'=>255),
			array('created_at, updated_at', 'safe'),
			array('user_id, email, is_subscribed, created_at, updated_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, email, is_subscribed, created_at, updated_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'Users', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'email' => Yii::t('app', 'Email'),
			'is_subscribed' => Yii::t('app', 'Is Subscribed'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('is_subscribed', $this->is_subscribed);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}