<?php

/**
 * This is the model base class for the table "configurations".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Configurations".
 *
 * Columns in table "configurations" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $paypal_partner
 * @property string $paypal_merchant_login
 * @property string $paypal_password
 * @property string $paypal_payment_mode
 * @property string $facebook_appid
 * @property string $facebook_secret
 * @property integer $status
 * @property string $last_updated_at
 *
 */
abstract class BaseConfigurations extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'configurations';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Configurations|Configurations', $n);
	}

	public static function representingColumn() {
		return 'paypal_partner';
	}

	public function rules() {
		return array(
			array('paypal_partner, paypal_merchant_login, paypal_password, facebook_appid, facebook_secret, last_updated_at', 'required'),
			array('status', 'numerical', 'integerOnly'=>true),
			array('paypal_partner, paypal_merchant_login, paypal_password, facebook_appid, facebook_secret', 'length', 'max'=>255),
			array('paypal_payment_mode', 'length', 'max'=>4),
			array('paypal_payment_mode, status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, paypal_partner, paypal_merchant_login, paypal_password, paypal_payment_mode, facebook_appid, facebook_secret, status, last_updated_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'paypal_partner' => Yii::t('app', 'Paypal Partner'),
			'paypal_merchant_login' => Yii::t('app', 'Paypal Merchant Login'),
			'paypal_password' => Yii::t('app', 'Paypal Password'),
			'paypal_payment_mode' => Yii::t('app', 'Paypal Payment Mode'),
			'facebook_appid' => Yii::t('app', 'Facebook Appid'),
			'facebook_secret' => Yii::t('app', 'Facebook Secret'),
			'status' => Yii::t('app', 'Status'),
			'last_updated_at' => Yii::t('app', 'Last Updated At'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('paypal_partner', $this->paypal_partner, true);
		$criteria->compare('paypal_merchant_login', $this->paypal_merchant_login, true);
		$criteria->compare('paypal_password', $this->paypal_password, true);
		$criteria->compare('paypal_payment_mode', $this->paypal_payment_mode, true);
		$criteria->compare('facebook_appid', $this->facebook_appid, true);
		$criteria->compare('facebook_secret', $this->facebook_secret, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('last_updated_at', $this->last_updated_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}