<?php

/**
 * This is the model base class for the table "system_config".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SystemConfig".
 *
 * Columns in table "system_config" available as properties of the model,
 * followed by relations of table "system_config" available as properties of the model.
 *
 * @property string $id
 * @property string $system_section_id
 * @property string $system_group_id
 * @property string $name
 * @property string $desc
 * @property string $value
 * @property string $input_type
 * @property string $input_options
 * @property integer $status
 * @property integer $position
 *
 * @property SystemGroup $systemGroup
 * @property SystemSection $systemSection
 */
abstract class BaseSystemConfig extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'system_config';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'SystemConfig|SystemConfigs', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('status, position', 'numerical', 'integerOnly'=>true),
			array('system_section_id, system_group_id', 'length', 'max'=>10),
			array('name', 'length', 'max'=>100),
			array('input_type', 'length', 'max'=>8),
			array('desc, value, input_options', 'safe'),
			array('system_section_id, system_group_id, name, desc, value, input_type, input_options, status, position', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, system_section_id, system_group_id, name, desc, value, input_type, input_options, status, position', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'systemGroup' => array(self::BELONGS_TO, 'SystemGroup', 'system_group_id'),
			'systemSection' => array(self::BELONGS_TO, 'SystemSection', 'system_section_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'system_section_id' => null,
			'system_group_id' => null,
			'name' => Yii::t('app', 'Name'),
			'desc' => Yii::t('app', 'Desc'),
			'value' => Yii::t('app', 'Value'),
			'input_type' => Yii::t('app', 'Input Type'),
			'input_options' => Yii::t('app', 'Input Options'),
			'status' => Yii::t('app', 'Status'),
			'position' => Yii::t('app', 'Position'),
			'systemGroup' => null,
			'systemSection' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('system_section_id', $this->system_section_id);
		$criteria->compare('system_group_id', $this->system_group_id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('desc', $this->desc, true);
		$criteria->compare('value', $this->value, true);
		$criteria->compare('input_type', $this->input_type, true);
		$criteria->compare('input_options', $this->input_options, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('position', $this->position);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}