<?php

/**
 * This is the model base class for the table "google_keys".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "GoogleKeys".
 *
 * Columns in table "google_keys" available as properties of the model,
 * followed by relations of table "google_keys" available as properties of the model.
 *
 * @property string $id
 * @property string $keyword
 *
 * @property GoogleNews[] $googleNews
 */
abstract class BaseGoogleKeys extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'google_keys';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'GoogleKeys|GoogleKeys', $n);
	}

	public static function representingColumn() {
		return 'keyword';
	}

	public function rules() {
		return array(
			array('keyword', 'required'),
			array('keyword', 'length', 'max'=>1000),
			array('id, keyword', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'googleNews' => array(self::HAS_MANY, 'GoogleNews', 'keyword'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'keyword' => Yii::t('app', 'Keyword'),
			'googleNews' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('keyword', $this->keyword, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}