<?php

/**
 * This is the model base class for the table "google_news".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "GoogleNews".
 *
 * Columns in table "google_news" available as properties of the model,
 * followed by relations of table "google_news" available as properties of the model.
 *
 * @property string $id
 * @property string $keyword
 * @property string $date
 * @property string $title
 * @property string $brief
 * @property string $link
 *
 * @property GoogleKeys $keyword0
 */
abstract class BaseGoogleNews extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'google_news';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'GoogleNews|GoogleNews', $n);
	}

	public static function representingColumn() {
		return 'date';
	}

	public function rules() {
		return array(
			array('keyword', 'required'),
			array('keyword', 'length', 'max'=>20),
			array('date, title, brief, link', 'safe'),
			array('date, title, brief, link', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, keyword, date, title, brief, link', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'keyword0' => array(self::BELONGS_TO, 'GoogleKeys', 'keyword'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'keyword' => null,
			'date' => Yii::t('app', 'Date'),
			'title' => Yii::t('app', 'Title'),
			'brief' => Yii::t('app', 'Brief'),
			'link' => Yii::t('app', 'Link'),
			'keyword0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('keyword', $this->keyword);
		$criteria->compare('date', $this->date, true);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('brief', $this->brief, true);
		$criteria->compare('link', $this->link, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}