<?php

// this contains the application parameters that can be maintained via GUI
$ssSiteURL = ($_SERVER['SERVER_NAME'] == "inheritx.dnsdynamic.com") ? $_SERVER['SERVER_NAME'] . ':8590' : $_SERVER['SERVER_NAME'];
return array(
    'title' => 'TwinkleStarDance',
    'adminEmail' => 'info@twinklestardance.com, amanda@tiffanydance.com, tiffany@tiffanydance.com',
    'adminEmail2' => 'joyce@tiffanydance.com', //'joyce@tiffanydance.com',
    'postsPerPage' => 10,
    'copyrightInfo' => 'Copyright &copy; 2009 by TwinkleStarDance.',
    'site_url' => 'http://' . $ssSiteURL, // LOCAL
    // PAYPAL MANAGER SETTINGS //
    'PAYPAL_URL' => 'https://payflowlink.paypal.com',
    'LOGIN' => 'Twinklestardance',
    'PARTNER' => 'PayPal',
    'PASSWORD' => 'test4444', //'brande191',
    'MODE' => 'live',   // test, live
    /*
      // PAYPAL MANAGER SETTINGS FOR TESTING //
      'PAYPAL_URL' => 'https://pilot-payflowlink.paypal.com',
      'LOGIN' => 'PrakashInx',
      'PARTNER' => 'PayPal',
     */

    // FACEBOOK APP SETTINGS //
    'FACEBOOK_APPID' => '316847528455060',
    'FACEBOOK_SECRET' => 'd7de4d2037f6efafa170320293c96404',
    
    'uploadDir' => 'uploads/',
    'noImagePath' => 'images/noimage.jpg',
    'uploadDirBasePath' => dirname(__FILE__) . DIRECTORY_SEPARATOR . '../../uploads/',
    'package_sub_prefix' => 'package_sub_',
    'user_prefix' => 'user_',
    'inst_prefix' => 'instructor_',
    'classes_prefix' => 'class_',
    'pckge_sub_thumb_width' => '198',
    'pckge_sub_thumb_height' => '149',
    'package_sub_front_width' => '298',
    'package_sub_front_height' => '238',
    'package_sub_details_width' => '298',
    'package_sub_details_height' => '237',
    'user_thumb_width' => '198',
    'user_thumb_height' => '149',
    'class_thumb_width' => '198',
    'class_thumb_height' => '149',
    'price_symbol' => "$",
    'admin_id' => 1,
    'user_type' => array('admin' => 1,
        'studio' => 2,
        'dancer' => 3,
        'instructor' => 4        
    ),
    'amPaymentStatus' => array(
        'pending' => '0',
        'paid' => '1',
        'failed' => '2'
    ),
    'displayamPaymentStatus' => array(
        '0' => 'Pending',
        '1' => 'Paid',
        '2' => 'Failed'
    ),
    'amSubPaymentStatus' => array(
        'not_applicable' => '-1',
        'pending' => '0',
        'paid' => '1',
        'failed' => '2',
        'due' => '3',
        'free' => '4'
    ),
    'amPaymentDuration' => array(
        'monthly' => '1',
        'yearly' => '2',
    ),
    'amPaymentType' => array(
        'Visa' => 'Visa',
        'MasterCard' => 'MasterCard',
    ),
    'amExpirationMonth' => array(
        '1' => '01',
        '2' => '02',
        '3' => '03',
        '4' => '04',
        '5' => '05',
        '6' => '06',
        '7' => '07',
        '8' => '08',
        '9' => '09',
        '10' => '10',
        '11' => '11',
        '12' => '12'
    ),
    'amExpirationYear' => array(
        '2013' => '2013',
        '2014' => '2014',
        '2015' => '2015',
        '2016' => '2016',
        '2017' => '2017',
        '2018' => '2018',
        '2019' => '2019',
        '2020' => '2020',
        '2021' => '2021',
        '2022' => '2022'
    ),
    'perPageLimit' => '8',
    'listPerPageLimit' => '9',
    'max_length_char_to_dispaly' => '30',
    'defaultIframeWidth' => '640px',
    'defaultDateFormat' => 'm/d/Y',
    'paymentMethod' => array(
//'0' => '---',
        '1' => 'Visa',
        '2' => 'Master Card',
        '3' => 'Check',
        '4' => 'Cash',
    ),
    'comparePaymentMethod' => array(
        'visa' => '1',
        'mc' => '2',
        'cheque' => '3',
        'cash' => '4',
    ),
    'defaultStatus' => array(
        '0' => 'No',
        '1' => 'Yes',
        '2' => 'Reject'
    ),
    'displayDuration' => array(
        '1' => 'Monthly',
        '2' => 'Yearly'
    ),
    'comparePaymentMode' => array(
        'single' => '1',
        'all' => '2'
    ),
    'default_country' => array('US' => 1),
    'displayPaymentOption' => array(
        '1' => 'Recurring',
        '2' => 'Full Payment'
    ),
    'displayUpfrontPaymentOption' => array(
        '2' => 'Full Payment'
    ),
    'displayRecurringRenewPaymentOption' => array(
        '1' => 'Recurring',
    ),
    'comparePaymentOption' => array(
        'recurring' => '1',
        'full' => '2',
    ),
    'displayPaymentMethods' => array(
        '1' => 'Credit / Debit Card',
        '2' => 'Check',
        '3' => 'Cash'
    ),
    'comparePaymentMethods' => array(
        'online' => '1',
        'cheque' => '2',
        'cash' => '3',
    ),
    'paymentErrorResponse' => array(
        '0' => 'Success',
        '1' => 'User authentication failed.',
        '2' => 'Invalid tender type. Your merchant bank account does not support the following credit card type that was submitted.',
        '3' => 'Invalid transaction type. Transaction type is not appropriate for this transaction. For example, you cannot credit an authorization-only transaction.',
        '4' => 'Invalid amount format. Use the format: “#####.##”  Do not include currency symbols or commas. For processors that do not support Account Verification, you will receive this RESULT code if you process a $0 transaction.',
        '5' => 'Invalid merchant information. Processor does not recognize your merchant account information. Contact your bank account acquirer to resolve this problem.',
        '6' => 'Invalid or unsupported currency code',
        '7' => 'Field format error: Start or next payment date must be a valid future date',
        '8' => 'Not a transaction server',
        '9' => 'Too many parameters or invalid stream',
        '10' => 'Too many line items',
        '11' => 'Client time-out waiting for response',
        '12' => 'Declined. Check the credit card number, expiration date, and transaction information to make sure they were entered correctly. If this does not resolve the problem, have the customer call their card issuing bank to resolve.',
        '13' => 'Referral. Transaction cannot be approved electronically but can be approved with a verbal authorization. Contact your merchant bank to obtain an authorization and submit a manual Voice Authorization transaction.',
        '14' => 'Invalid Client Certification ID.',
        '19' => 'Original transaction ID not found.',
        '20' => 'Cannot find the customer reference number',
        '22' => 'Invalid ABA number',
        '23' => 'Invalid account number. Check credit card number and re-submit.',
        '24' => 'Invalid expiration date. Check and re-submit.',
        '25' => 'Invalid Host Mapping. You are trying to process a tender type such as Discover Card, but you are not set up with your merchant bank to accept this card type.',
        '26' => 'Invalid vendor account',
        '27' => 'Insufficient partner permissions',
        '28' => 'Insufficient user permissions',
        '29' => 'Invalid XML document. This could be caused by an unrecognized XML tag or a bad XML format that cannot be parsed by the system.',
        '30' => 'Duplicate transaction',
        '31' => 'Error in adding the recurring profile',
        '32' => 'Error in modifying the recurring profile',
        '33' => 'Error in canceling the recurring profile',
        '34' => 'Error in forcing the recurring profile',
        '35' => 'Error in reactivating the recurring profile',
        '36' => 'OLTP Transaction failed',
        '37' => 'Invalid recurring profile ID',
        '50' => 'Insufficient funds available in account',
        '51' => 'Exceeds per transaction limit',
        '99' => 'General error.',
        '100' => 'Transaction type not supported by host',
        '101' => 'Time-out value too small',
        '102' => 'Processor not available',
        '103' => 'Error reading response from host',
        '104' => 'Timeout waiting for processor response. Try your transaction again.',
        '105' => 'Credit error. Make sure you have not already credited this transaction, or that this transaction ID is for a creditable transaction. (For example, you cannot credit an authorization.)',
        '106' => 'Host not available',
        '107' => 'Duplicate suppression time-out',
        '108' => 'Void error.',
        '109' => 'Time-out waiting for host response',
        '110' => 'Referenced auth (against order) Error',
        '111' => 'Capture error. Either an attempt to capture a transaction that is not an authorization transaction type, or an attempt to capture an authorization transaction that has already been captured.',
        '112' => 'Failed AVS check. Address and ZIP code do not match. An authorization may still exist on the cardholder’s account.',
        '113' => 'Merchant sale total will exceed the sales cap with current transaction. ACH transactions only.',
        '114' => 'Card Security Code mismatch. An authorization may still exist on the cardholder’s account.',
        '115' => 'System busy, try again later',
        '116' => 'PayPal Internal error. Failed to lock terminal number',
        '117' => 'Failed merchant rule check',
        '118' => 'Invalid keywords found in string fields',
        '119' => 'General failure within PIM Adapter',
        '120' => 'Attempt to reference a failed transaction',
        '121' => 'Not enabled for feature',
        '122' => 'Merchant sale total will exceed the credit cap with current transaction. ACH transactions only.',
        '125' => 'Fraud Protection Services Filter — Declined by filters',
        '126' => 'Fraud Protection Services Filter — Flagged for review by filters',
        '127' => 'Fraud Protection Services Filter — Not processed by filters',
        '128' => 'Fraud Protection Services Filter — Declined by merchant after being flagged for review by filters',
        '131' => 'Version 1 Payflow SDK client no longer supported. Upgrade to the most recent version of the Payflow client.',
        '132' => 'Card has not been submitted for update',
        '133' => 'Data mismatch in HTTP retry request',
        '150' => 'Issuing bank timed out',
        '151' => 'Issuing bank unavailable',
        '200' => 'Reauth error',
        '201' => 'Order error',
        '402' => 'PIM Adapter Unavailable',
        '403' => 'PIM Adapter stream error',
        '404' => 'PIM Adapter Timeout',
        '600' => 'Cybercash Batch Error',
        '601' => 'Cybercash Query Error',
        '1000' => 'Generic host error. This is a generic message returned by your credit card processor.',
        '1001' => 'Buyer Authentication unavailable',
        '1002' => 'Buyer Authentication — Transaction timeout',
        '1003' => 'Buyer Authentication — Invalid client version',
        '1004' => 'Buyer Authentication — Invalid timeout value',
        '1011' => 'Buyer Authentication unavailable',
        '1012' => 'Buyer Authentication unavailable',
        '1013' => 'Buyer Authentication unavailable',
        '1014' => 'Buyer Authentication — Merchant is not enrolled for Buyer Authentication Service (3-D Secure).',
        '1016' => 'Buyer Authentication — 3-D Secure error response received. Instead of receiving a PARes response to a Validate Authentication transaction, an error response was received.',
        '1017' => 'Buyer Authentication — 3-D Secure error response is invalid. An error response is received and the response is not well formed for a Validate Authentication transaction.',
        '1021' => 'Buyer Authentication — Invalid card type',
        '1022' => 'Buyer Authentication — Invalid or missing currency code',
        '1023' => 'Buyer Authentication — merchant status for 3D secure is invalid',
        '1041' => 'Buyer Authentication — Validate Authentication failed: missing or invalid PARES',
        '1042' => 'Buyer Authentication — Validate Authentication failed: PARES format is invalid',
        '1043' => 'Buyer Authentication — Validate Authentication failed: Cannot find successful Verify Enrollment',
        '1044' => 'Buyer Authentication — Validate Authentication failed: Signature validation failed for PARES',
        '1045' => 'Buyer Authentication — Validate Authentication failed: Mismatched or invalid amount in PARES',
        '1046' => 'Buyer Authentication — Validate Authentication failed: Mismatched or invalid acquirer in PARES',
        '1047' => 'Buyer Authentication — Validate Authentication failed: Mismatched or invalid Merchant ID in PARES',
        '1048' => 'Buyer Authentication — Validate Authentication failed: Mismatched or invalid card number in PARES',
        '1049' => 'Buyer Authentication — Validate Authentication failed: Mismatched or invalid currency code in PARES',
        '1050' => 'Buyer Authentication — Validate Authentication failed: Mismatched or invalid XID in PARES',
        '1051' => 'Buyer Authentication — Validate Authentication failed: Mismatched or invalid order date in PARES',
        '1052' => 'Buyer Authentication — Validate Authentication failed: This PARES was already validated for a previous Validate Authentication transaction',
    ),
    'paymentHistoryTransStates' => array(
        '0' => 'Capture failed (an error occurred while trying to capture an authorisation because the transaction was already captured)',
        '1' => 'General error state',
        '3' => 'Authorisation approved',
        '6' => 'Settlement pending (transaction is scheduled to be settled)',
        '7' => 'Settlement in progress (transaction involved in a currently ongoing settlement)',
        '8' => 'Settled successfully',
        '9' => 'Authorisation captured (once an authorisation type transaction is captured)',
        '10' => 'Capture failed (an error occurred while trying to capture an authorisation because the transaction was already captured)',
        '11' => 'Failed to settle',
        '12' => 'Unsettled transaction because of incorrect account information',
        '14' => 'For various reasons, the batch containing this transaction failed settlement',
        '15' => 'Settlement incomplete due to a charge back',
        '16' => 'Merchant ACH settlement failed; (need to manually collect it)',
        '106' => 'Unknown Status Transaction - Transactions not settled',
        '206' => 'Transactions on hold pending customer intervention',
    ),
    'paymentHistoryTenderType' => array(
        'C' => 'Credit Card',
        'A' => 'Bank Account',
    ),
    'paymentMode' => array(
        '1' => 'Monthly Recurring',
        '2' => 'Yearly Payment',
        '3' => 'Monthly Full Payment'
    ),
    'paypalMode' => array(
        'live' => 'Live',
        'test' => 'Test'
    ),
);
